// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import StockHistoriesController from "./stock_histories_controller.js"
application.register("stock-histories", StockHistoriesController)

import StocksController from "./stocks_controller.js"
application.register("stocks", StocksController)

import ToastController from "./toast_controller.js"
application.register("toast", ToastController)
